# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Interesting Times....
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  May you come up with an interesting description..
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyeminSsong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 'UA-131540516-1' # Substitute this with your own GA key
twitter_username: jekyllrb
github_username:  jekyll
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections_dir: _collections

collections:
  columns:
    output: true
  heros:
    output: true


# -----------------------
# Main article (Hero Section)
# -----------------------
heros:
  - title: "Farewell to the Old Guard"
    image: "/assets/images/old_guard.jpg"
    subtitle: "Napoleon’s Final Goodbye"
    lead: "The Emperor of France and would-be ruler of Europe said goodbye to the Old Guard after his failed invasion of Russia and defeat by the Allies."
    date: "20/04/14"
    body: |
      Soldiers of my Old Guard: I bid you farewell.
      For twenty years I have constantly accompanied you on the road to honour and glory.
      In these latter times, as in the days of our prosperity, you have never ceased to be models of courage and fidelity.
      With men such as you, our cause could not be lost; but the war has been too long, and the nation's strength is exhausted.
      I now go to join my son.
    position: "left"

  - title: "The War of the Worlds"
    image: "/assets/images/Anti-War.png"
    subtitle: "Orson Welles’ Broadcast Shocked a Nation"
    lead: "The fictional radio drama caused panic across America as listeners believed a Martian invasion was real."
    date: "30/10/38"
    body: |
      Orson Welles’ adaptation of H.G. Wells’ novel ‘The War of the Worlds’ aired on CBS Radio,
      convincing thousands that aliens had landed on Earth.
      Streets emptied, phone lines jammed, and the power of media was revealed like never before.
      The chaos remains one of the most infamous moments in broadcast history.
    position: "center"

  - title: "Yes We Can"
    image: "/assets/images/yes_we_can.jpg"
    subtitle: "A New Dawn in American Politics"
    lead: "President-elect Barack Obama spoke to the world from his home city of Chicago as he became the first black president of the United States."
    date: "05/11/08"
    body: |
      Hello, Chicago.
      If there is anyone out there who still doubts that America is a place where all things are possible,
      who still wonders if the dream of our founders is alive in our time, tonight is your answer.
      Hope ? against fear, unity over division ? marked the beginning of a new chapter in modern democracy.
    position: "right"

# -----------------------
# Bottom Articles (Columns Section)
# -----------------------
columns:
  - title: "Digital Minimalism"
    image: "/assets/images/minimalism.jpg"
    text: "A quiet resistance against the noise of the modern internet age. Cal Newport’s philosophy inspires many to reclaim focus in a distracted world."

  - title: "Inside Tesla’s Neural Factory"
    image: "/assets/images/tesla.jpg"
    text: "Inside the assembly lines of tomorrow ? how automation, neural networks, and human ingenuity reshape innovation."

  - title: "The Art of Vinyl"
    image: "/assets/images/vinyl.jpg"
    text: "Analog nostalgia meets digital precision: why people still find magic in spinning records."

  - title: "The Future of Food"
    image: "/assets/images/future_food.jpg"
    text: "From lab-grown meat to vertical farms, a look into the sustainable plates of tomorrow."

# Social media
twitter: twitter
github: github
linkedin: linkedin
facebook: facebook
