# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Interesting Times
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  May you come up with an interesting description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hyeminSsong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 'UA-131540516-1' # Substitute this with your own GA key
twitter_username: jekyllrb
github_username:  jekyll
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# -----------------------
# Navigation bar (Top menu)
# -----------------------
nav:
  - name: "GITHUB"
    url: "https://github.com/hyeminSsong"
    target: "_blank"

  - name: "게시글"
    subitems:
      - name: "Dev"
        url: "/categories/dev/"
      - name: "DB"
        url: "/categories/db/"
      - name: "OS"
        url: "/categories/os/"
      - name: "Net"
        url: "/categories/net/"
      - name: "Algo"
        url: "/categories/algo/"
      - name: "Thoughts"
        url: "/categories/thoughts/"

  - name: "About"
    url: "/about/"

  - name: "뉴스"
    url: "/news/"

# -----------------------
# Main article (Hero Section)
# -----------------------
heros:
  - title: "Why I Build Systems That Listen"
    image: "/assets/images/old_guard.jpg"
    subtitle: "현장에서 배운 한가지, 이번주의 생각"
    lead: "The Emperor of France and would-be ruler of Europe said goodbye to the Old Guard after his failed invasion of Russia and defeat by the Allies."
    date: "20/04/14"
    body: |
      Soldiers of my Old Guard: I bid you farewell.
      For twenty years I have constantly accompanied you on the road to honour and glory.
      In these latter times, as in the days of our prosperity, you have never ceased to be models of courage and fidelity.
      With men such as you, our cause could not be lost; but the war has been too long, and the nation's strength is exhausted.
      I now go to join my son.
    position: "left"

  - title: "Editor’s Note"
    image: "/assets/images/Anti-War.png"
    subtitle: "In a world full of data, she found meaning in patterns and people."
    lead: "The fictional radio drama caused panic across America as listeners believed a Martian invasion was real."
    date: "24/10/25"
    body: |
      This page is written by Hyemin Song, a developer who believes every system tells a human story.
      She writes about the invisible work behind everyday data.
    position: "center"

  - title: "Yes We Can"
    image: "/assets/images/yes_we_can.jpg"
    subtitle: "A New Dawn in American Politics"
    lead: "President-elect Barack Obama spoke to the world from his home city of Chicago as he became the first black president of the United States."
    date: "05/11/08"
    body: |
      Hello, Chicago.
      If there is anyone out there who still doubts that America is a place where all things are possible,
      who still wonders if the dream of our founders is alive in our time, tonight is your answer.
      Hope - against fear, unity over division - marked the beginning of a new chapter in modern democracy.
    position: "right"

# Social media
twitter: twitter
github: github
linkedin: linkedin
facebook: facebook

# 페이지 개수
pagination:
  enabled: true
  per_page: 4
  paginate_path: "categories/:num"

