title: "Hyemin Song’s Blog"
name: "Hyemin Song"
user_title: "Backend Developer"
user_description: "Java/JS/SQL 좋아하는 개발자"
email: "hyeminsSsong@example.com"

url: "https://hyeminSsong.github.io"
baseurl: ""

# 테마 관련
theme_settings:
  author: "Hyemin Song"
  description: "A newspaper-style developer blog."
  contact_email: "hyeminsSsong@example.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# 신문 테마가 필요로 하는 기본 경로
collections:
  posts:
    output: true
